version: "3.8"

services:
  data-analysis:
    image: python:3.13-bookworm
    container_name: data-analysis
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - PYTHONPATH=/app
    command: >
      sh -c "
        pip install --no-cache-dir -r requirements.txt &&
        tail -f /dev/null
      "
